diff_drive_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    left_wheel_names: ["wheel_front_left_joint", "wheel_rear_left_joint"]
    right_wheel_names: ["wheel_front_right_joint", "wheel_rear_right_joint"]
    wheel_separation: 0.6
    wheel_radius: 0.15
    cmd_vel_timeout: 0.5
    use_stamped_vel: false
    base_frame_id: base_link
    publish_rate: 50.0
    enable_odom_tf: true

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
